# Generated by Django 3.0.5 on 2020-09-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MD', 'moderator'), ('US', 'user'), ('AD', 'admin')], default='user', max_length=2),
        ),
    ]
