# Generated by Django 3.0.5 on 2020-09-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200929_1548'),
        ('api', '0002_auto_20200929_1911'),
    ]

    operations = [
    ]
