# Generated by Django 3.0.5 on 2020-09-30 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20200930_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.Titles', verbose_name='произведение'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.Titles', verbose_name='произведение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MD', 'moderator'), ('AD', 'admin'), ('US', 'user')], default='user', max_length=2),
        ),
    ]
