# Generated by Django 3.0.5 on 2020-09-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200930_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MD', 'moderator'), ('US', 'user'), ('AD', 'admin')], default='user', max_length=2),
        ),
    ]
