# Generated by Django 3.0.5 on 2020-09-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200930_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'admin'), ('MD', 'moderator'), ('US', 'user')], default='user', max_length=2),
        ),
    ]
