# Generated by Django 3.0.5 on 2020-10-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201001_0012'),
        ('api', '0008_auto_20200930_1402'),
    ]

    operations = [
    ]
